ALTER TABLE "public"."scanword_issue_svg_settings"
  ADD COLUMN "templateCellSizeMm" DOUBLE PRECISION NOT NULL DEFAULT 11,
  ADD COLUMN "answerCellSizeMm" DOUBLE PRECISION NOT NULL DEFAULT 10,
  ADD COLUMN "type0CellSizeMm" DOUBLE PRECISION NOT NULL DEFAULT 8.5;
