import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import { getServerSession } from "next-auth";
import { Suspense } from "react";
import "./globals.css";
import { authOptions } from "@/auth";
import { ReactGrabInitializer } from "@/components/dev/ReactGrabInitializer";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/providers/AuthProvider";
import { QueryProvider } from "@/providers/QueryProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const SUPPORTED_LOCALES = new Set(["ru", "en", "uk"]);

export const metadata: Metadata = {
  title: "CrossNext",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-48x48.png", sizes: "48x48", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const requestHeaders = await headers();
  const localeFromHeader = requestHeaders.get("X-NEXT-INTL-LOCALE");
  const cspNonce = requestHeaders.get("x-csp-nonce") ?? undefined;
  const htmlLang = localeFromHeader && SUPPORTED_LOCALES.has(localeFromHeader) ? localeFromHeader : "ru";
  return (
    <html lang={htmlLang} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} relative min-h-screen bg-background antialiased`}>
        <div className="page-glow-layer" aria-hidden>
          <div className="page-glow-top" />
          <div className="page-glow-bottom" />
          <div className="page-glow-radial" />
        </div>
        <ThemeProvider nonce={cspNonce}>
          <div className="relative z-10">
            <QueryProvider>
              <AuthProvider session={session}>
                <Suspense fallback={<main suppressHydrationWarning />}>
                  <main suppressHydrationWarning>{children}</main>
                </Suspense>
              </AuthProvider>
            </QueryProvider>
          </div>
          <ReactGrabInitializer />
          <Toaster richColors position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
