onlyBuiltDependencies:
  - '@prisma/client'
  - prisma
  - '@prisma/engines'
  - esbuild

overrides:
  mysql2: ^3.23.1
  '@prisma/dev>hono': 4.13.5
  '@napi-rs/cli>js-yaml': 5.4.1
  'ajv>fast-uri': 4.1.5
  'minimatch>brace-expansion': 5.0.12
  '@hono/node-server': ^2.0.5
  '@hono/node-server@<2.0.5': '>=2.0.5'
  archiver-utils>lodash: ^4.18.0
  body-parser@>=2.0.0 <2.3.0: '>=2.3.0'
  brace-expansion@<=5.0.8: '>=5.0.9'
  brace-expansion@>=2.0.0 <2.1.2: '>=2.1.2'
  brace-expansion@>=4.0.0 <5.0.9: '>=5.0.9'
  deepmerge-ts@<8.0.0: '>=8.0.0'
  diff: ^4.0.4
  esbuild: ^0.28.1
  fast-uri: ^3.1.4
  fast-uri@>=3.0.0 <3.1.3: '>=3.1.3'
  fast-uri@>=3.0.0 <=3.1.4: '>=3.1.5'
  fast-uri@>=4.0.0 <4.1.2: '>=4.1.2'
  glob>minimatch: ^9.0.6
  hono: ^4.12.27
  hono@<4.12.34: '>=4.12.34'
  hono@>=3.8.0 <4.12.34: '>=4.12.34'
  hono@>=4.11.8 <4.12.27: '>=4.12.27'
  hono@>=4.12.0 <4.12.34: '>=4.12.34'
  hono@>=4.3.3 <4.12.27: '>=4.12.27'
  hono@>=4.7.0 <4.12.34: '>=4.12.34'
  js-yaml: ^4.3.0
  js-yaml@>=4.0.0 <4.3.0: '>=4.3.0'
  qs: ^6.16.0
  readdir-glob>minimatch: ^5.1.7
  router>path-to-regexp: ^8.4.2
  sharp@<0.35.0: '>=0.35.0'
  valibot: ^1.4.2
  valibot@<=1.4.1: '>=1.4.2'
